/* ATRALAB SongLab V1 — static frontend; privileged operations only through Edge Functions. */
(() => {
  'use strict';
  const API = 'https://pcpsbrnhfhzkjlnstgfr.supabase.co/functions/v1/';
  const $ = id => document.getElementById(id);
  const el = (tag, cls, text) => { const n = document.createElement(tag); if(cls) n.className = cls; if(text !== undefined) n.textContent = String(text); return n; };
  const state = { config: null, session: null, validPrompt: false, previewed: false, busy: false, tasks: [], songs: [], admin: false, poll: null, currentTask: null, requestId: null, pollInFlight: false, elapsedStart: null, liveAudio: null };
  const MAX = { title: 200, lyrics: 5000, extra: 300, prompt: 1024, instruments: 4 };
  const uuid = () => typeof crypto.randomUUID === 'function' ? crypto.randomUUID() : 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {const r=crypto.getRandomValues(new Uint8Array(1))[0]&15;return (c==='x'?r:(r&3|8)).toString(16);});
  const fmtDuration = ms => Number.isFinite(Number(ms)) && ms !== null ? `${Math.floor(Number(ms)/60000)}:${String(Math.floor(Number(ms)%60000/1000)).padStart(2,'0')}` : '—';
  const fmtSize = bytes => Number.isFinite(Number(bytes)) && bytes !== null ? `${(Number(bytes)/1048576).toFixed(1).replace('.',',')} MB` : '—';
  const displayDate = date => date ? new Intl.DateTimeFormat('it-IT',{dateStyle:'short',timeStyle:'short',timeZone:'Europe/Rome'}).format(new Date(date)) : '—';
  const cleanFile = text => (text || 'Canzone').replace(/[\\/:*?"<>|\x00-\x1f]/g,' ').replace(/\s+/g,' ').trim().slice(0,90) || 'Canzone';
  function fileName(song) {const d = new Date(song.created_at || Date.now());const f = new Intl.DateTimeFormat('en-GB',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23',timeZone:'Europe/Rome'}).formatToParts(d);const parts=Object.fromEntries(f.map(p=>[p.type,p.value]));return `${cleanFile(song.title)}_${parts.year}${parts.month}${parts.day}${parts.hour}${parts.minute}.mp3`;}
  function notify(message, kind='info') {const box=$('sl-notice');box.textContent=message;box.dataset.kind=kind;box.hidden=false;}
  function clearNotice(){ $('sl-notice').hidden=true; }
  const setBusy = on => {state.busy=on;$('sl-preview').disabled=on;$('sl-refresh').disabled=on;$('sl-generate').disabled=on || !canGenerate();};
  async function login() { if(typeof window.getAtralabSupabaseSession !== 'function') throw Error('Sessione ATRALAB non disponibile. Ricarica la pagina e verifica include.js.'); const session=await window.getAtralabSupabaseSession(); if(!session?.access_token) throw Error('Accedi con OTP ATRALAB prima di utilizzare SongLab.'); state.session=session;return session; }
  async function call(fn, data) {const session=await login();const r=await fetch(API+fn,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify(data),cache:'no-store'});let body;try{body=await r.json();}catch{body={error:'invalid_response'};}if(!r.ok) {const e=Error(explainError(body.error) + ` (HTTP ${r.status})`);e.code=body.error;e.data=body;throw e;}return body;}
  function explainError(code) {return ({login_required:'Accesso scaduto: esegui di nuovo il login.',access_denied:'Non hai i permessi per questa operazione.',busy:'È già in corso una generazione: controlla la Libreria.',quota_exceeded:'Limite giornaliero di generazioni raggiunto.',storage_limit_reached:'Spazio SongLab insufficiente.',storage_full:'Spazio SongLab esaurito.',invalid_input:'Controlla i campi inseriti.',invalid_song_id:'Identificativo canzone non valido.',task_not_ready:'La canzone non è ancora pronta.',save_already_in_progress:'Salvataggio già in corso.',mureka_status_unavailable:'Mureka non risponde al controllo di stato.',audio_unavailable:'Audio non disponibile, riprova.',translation_failed:'Traduzione non riuscita.'})[code] || String(code || 'Operazione non riuscita');}
  function options(key) {const opts=state.config?.options?.[key];return Array.isArray(opts)?opts:Array.isArray(state.config?.[key])?state.config[key]:[];}
  function fillSettings() {for(const key of ['genre','mood','tempo','energy','production','voice']) {const select=$('sl-'+key);select.replaceChildren();for(const choice of options(key)){const op=el('option');op.value=String(choice.value ?? 'auto');op.textContent=choice.label ?? op.value;select.append(op);} if(!select.options.length){const op=el('option',null,'Automatico');op.value='auto';select.append(op);}select.value=state.config.defaults?.[key] ?? 'auto';}
    const holder=$('sl-instruments');holder.replaceChildren();for(const choice of options('instruments')) {const label=el('label');const input=el('input');input.type='checkbox';input.value=String(choice.value);input.dataset.instrument='true';const caption=el('span',null,choice.label ?? choice.value);label.append(input,caption);holder.append(label);input.addEventListener('change',()=>{const checked=instrumentValues();const limit=state.config?.limits?.maxInstruments || MAX.instruments;if(checked.length>limit){input.checked=false;notify(`Puoi scegliere al massimo ${limit} strumenti.`);return;}updateInstrumentCounter();invalidatePrompt();});}updateInstrumentCounter();const lim=state.config?.limits || {}; $('sl-title').maxLength=lim.titleMaxChars||MAX.title;$('sl-lyrics').maxLength=lim.lyricsMaxChars||MAX.lyrics;$('sl-extra').maxLength=lim.extraMaxChars||MAX.extra;$('sl-prompt').maxLength=lim.promptMaxChars||MAX.prompt;updateCounts();}
  function instrumentValues(){return [...document.querySelectorAll('[data-instrument]:checked')].map(n=>n.value);}
  function updateInstrumentCounter(){const chosen=instrumentValues().length;const max=state.config?.limits?.maxInstruments||4;$('sl-instruments-counter').textContent=`${chosen} / ${max}`;document.querySelectorAll('[data-instrument]:not(:checked)').forEach(n=>n.disabled=chosen>=max);}
  function settings() {const v={};for(const key of ['genre','mood','tempo','energy','production','voice'])v[key]=$('sl-'+key).value;v.instruments=instrumentValues();v.extra=$('sl-extra').value.trim();return v;}
  function invalidatePrompt(){if(state.previewed){state.validPrompt=false;$('sl-prompt-badge').textContent='Da aggiornare';}setBusy(state.busy);}
  function updateCounts(){const n=$('sl-lyrics').value.length;$('sl-lyrics-count').textContent=`${n} / ${$('sl-lyrics').maxLength}`;$('sl-prompt-count').textContent=`${$('sl-prompt').value.length} / ${$('sl-prompt').maxLength}`;}
  function canGenerate(){const limit=state.config?.limits||{};return state.validPrompt && !!$('sl-title').value.trim() && !!$('sl-lyrics').value.trim() && $('sl-title').value.trim().length<=(limit.titleMaxChars||MAX.title) && $('sl-lyrics').value.length<=(limit.lyricsMaxChars||MAX.lyrics) && !!$('sl-prompt').value.trim() && $('sl-prompt').value.length<=(limit.promptMaxChars||MAX.prompt);}
  function descriptor(key,value) { if(!value || value==='auto')return ''; const opt=options(key).find(o=>String(o.value)===String(value));return opt?.en || ''; }
  function buildPrompt(extraEnglish) {const v=settings();const pieces=[];const order=state.config?.promptOrder || ['genre','mood','tempo','energy','instruments','production','extra'];for(const key of order){if(key==='extra'){if(extraEnglish) pieces.push(extraEnglish);continue;}if(key==='instruments'){const items=v.instruments.map(x=>descriptor('instruments',x)).filter(Boolean);if(items.length)pieces.push(`instruments: ${items.join(', ')}`);continue;}if(key==='voice')continue;const s=descriptor(key,v[key]);if(s)pieces.push(s);}if(!pieces.length)pieces.push('A balanced, melodic song with natural arrangement');return pieces.join(', ');}
  async function preparePrompt(){if(state.busy)return;const previous=$('sl-prompt').value.trim();if(state.previewed&&previous&&!state.validPrompt&&!window.confirm('Aggiornare il prompt? Le tue modifiche manuali al prompt attuale saranno sostituite.'))return;setBusy(true);try{let translated='';const extra=$('sl-extra').value.trim();if(extra){const res=await call('songlab-translate',{action:'translate',text:extra});translated=(res.translation || res.translated_text || res.english || res.text || '').trim();if(!translated)throw Error('Traduzione vuota. Anteprima non aggiornata.');}const prompt=buildPrompt(translated);if(prompt.length>($('sl-prompt').maxLength||MAX.prompt))throw Error('Il prompt supera 1.024 caratteri: riduci le indicazioni extra.');$('sl-prompt').value=prompt;$('sl-prompt-area').hidden=false;state.validPrompt=true;state.previewed=true;$('sl-prompt-badge').textContent='Aggiornato';updateCounts();notify('Anteprima pronta. Controlla il prompt prima di generare.','success');}catch(e){notify(e.message,'error');}finally{setBusy(false);}}
  function aiPrompt(){const get=id=>$(id).value.trim();return ['Scrivi il testo ORIGINALE di una canzone cantabile, pronto da incollare in SongLab.','Lingua: '+get('sl-ai-lang')+'.','Argomento: '+(get('sl-ai-topic')||'libero')+'.','Storia, dettagli e messaggio: '+(get('sl-ai-story')||'da proporre')+'.','Emozione: '+(get('sl-ai-emotion')||'libera')+'.','Stile del testo: '+(get('sl-ai-style')||'naturale e memorabile')+'.','Usa le etichette [Verse 1], [Chorus], [Verse 2], [Bridge], [Final Chorus], [Outro]. Scrivi strofe musicali e un ritornello memorabile, evitando cliché e imitazioni di artisti esistenti.','Restituisci SOLO il testo da cantare, con le etichette di sezione e senza spiegazioni. Massimo 5000 caratteri, preferibilmente almeno 300.'].join('\n');}
  async function copyAi(){const prompt=aiPrompt();try{await navigator.clipboard.writeText(prompt);notify('Prompt copiato: incollalo nella tua AI preferita.','success');}catch{const txt=window.prompt('Copia questo prompt:',prompt);if(txt!==null)notify('Prompt pronto per la copia.');}}
  function activate(tab){const library=tab==='library';$('sl-create').hidden=library;$('sl-library').hidden=!library;$('sl-tab-create').classList.toggle('is-active',!library);$('sl-tab-library').classList.toggle('is-active',library);$('sl-tab-create').setAttribute('aria-selected',String(!library));$('sl-tab-library').setAttribute('aria-selected',String(library));if(library)refreshLibrary().catch(e=>notify(e.message,'error'));}
  function stageText(status){return ({reserved:'Prenotazione',submitting:'Avvio',processing:'Generazione in corso',timeout:'Tempo di attesa superato',ready:'Pronta da salvare',saving:'Salvataggio MP3 in corso',saved:'Salvata',failed:'Non riuscita',start_unknown:'Avvio da verificare'})[status]||status||'In attesa';}
  function updateProgress(task){$('sl-progress').hidden=false;$('sl-progress-text').textContent=stageText(task.status)+(task.status==='saved'?' — La trovi nella tua libreria.':'');$('sl-elapsed').textContent=state.elapsedStart && ['processing','submitting','reserved'].includes(task.status)?`Tempo trascorso: ${Math.floor((Date.now()-state.elapsedStart)/60000)}m ${String(Math.floor((Date.now()-state.elapsedStart)/1000)%60).padStart(2,'0')}s`:'';}
  async function startGeneration(event){event.preventDefault();if(state.busy || !canGenerate())return;const prompt=$('sl-prompt').value.trim(),title=$('sl-title').value.trim(),lyrics=$('sl-lyrics').value.trim();const msg=`Avviare UNA generazione reale con Mureka?\n\nTitolo: ${title}\nQuesta operazione utilizza un credito Mureka e uno degli avvii giornalieri disponibili. Il salvataggio del brano sarà separato e manuale.`;if(!window.confirm(msg))return;setBusy(true);try{if(!state.requestId)state.requestId=uuid();const payload={action:'generate',request_id:state.requestId,title,lyrics,music_prompt:prompt,music_settings:settings()};const voice=settings().voice;if(voice==='male'||voice==='female')payload.gender=voice;const result=await call('songlab-generate',payload);if(result.outcome==='busy'||result.outcome==='quota_exceeded'){notify(explainError(result.outcome),'error');state.requestId=null;return;}if(result.task_id){state.currentTask=result.task_id;state.elapsedStart=Date.now();updateProgress({status:'processing'});notify('Richiesta registrata. Segui lo stato nella Libreria; non avviare una seconda generazione.','success');state.requestId=null;await refreshLibrary();beginPolling();}else notify(`Risposta di generazione: ${result.outcome||'nessun task restituito'}`,'error');}catch(e){notify(`${e.message}\nSe la richiesta è partita ma la risposta è incerta, NON ripetere automaticamente l'avvio: controlla prima la Libreria.`,'error');}finally{setBusy(false);}}
  function beginPolling(){if(state.poll)clearInterval(state.poll);state.poll=setInterval(()=>checkActive().catch(e=>notify(e.message,'error')),6000);checkActive().catch(e=>notify(e.message,'error'));}
  async function checkActive(){if(state.pollInFlight || document.hidden)return;state.pollInFlight=true;try{await refreshLibrary();const pending=state.tasks.filter(t=>['processing','submitting','reserved'].includes(t.status));for(const t of pending){if(t.status==='processing'){const result=await call('songlab-status-save',{action:'status',task_id:t.task_id});if(t.task_id===state.currentTask)updateProgress(result);if(['ready','saved','failed','timeout','start_unknown'].includes(result.status)){if(result.status==='ready')notify('Canzone pronta! Apri la Libreria e premi “Salva canzone”.','success');if(result.status==='timeout')notify('Attesa scaduta: usa “Controlla stato” in Libreria.','error');await refreshLibrary();}}}if(!state.tasks.some(t=>['processing','submitting','reserved'].includes(t.status))){clearInterval(state.poll);state.poll=null;}}finally{state.pollInFlight=false;}}
  async function refreshLibrary(){const data=await call('songlab-library',{action:'list'});state.songs=Array.isArray(data.songs)?data.songs:[];state.tasks=Array.isArray(data.tasks)?data.tasks:[];state.admin=!!data.admin;$('sl-library-count').textContent=state.songs.length ? String(state.songs.length):'';renderUsage(data.usage||{});renderTasks();renderSongs();const active=state.tasks.find(t=>['processing','submitting','reserved'].includes(t.status));if(active&&!state.poll)beginPolling();}
  function renderUsage(u){const holder=$('sl-usage');holder.replaceChildren();const used = u.used_today ?? u.today_used ?? u.generations_today;const max = u.daily_limit ?? u.limit_today ?? 5;const available = u.remaining_today ?? (used == null ? null : Math.max(0,Number(max)-Number(used)));$('sl-quota').textContent=available==null?'Disponibilità: —':`Avvii rimasti oggi: ${available} / ${max}`;if(available!=null)holder.append(el('span',null,`Generazioni disponibili oggi: ${available} / ${max}`));if(state.admin){const bytes=u.storage_used_bytes ?? u.used_bytes ?? u.storage_bytes;if(bytes!=null)holder.append(el('span',null,`Archivio: ${fmtSize(bytes)}`));holder.append(el('span',null,`Brani salvati: ${state.songs.length}`));}}
  function actionButton(text,onClick,kind='sl-ghost'){const b=el('button',`sl-btn ${kind} sl-smallbtn`,text);b.type='button';b.addEventListener('click',async()=>{if(b.disabled)return;b.disabled=true;try{await onClick();}catch(e){notify(e.message,'error');}finally{b.disabled=false;}});return b;}
  function renderTasks(){const holder=$('sl-tasks');holder.replaceChildren();const tasks=state.tasks.filter(t=>!['saved','failed'].includes(t.status));const order={ready:0,saving:1,timeout:2,start_unknown:3,processing:4,submitting:5,reserved:6};tasks.sort((a,b)=>(order[a.status]??9)-(order[b.status]??9));for(const task of tasks){const row=el('article','sl-item');row.append(el('h3','sl-item-title',task.title||'Canzone senza titolo'));row.append(el('div','sl-meta',`${stageText(task.status)} · ${displayDate(task.created_at)}${state.admin&&task.owner_email?' · '+task.owner_email:''}`));const actions=el('div','sl-item-actions');if(task.status==='ready')actions.append(actionButton('Salva canzone',async()=>{if(!window.confirm(`Salvare il brano “${task.title||'Canzone'}” come MP3 privato nella Libreria?`))return;notify('Salvataggio in corso, attendi...');await call('songlab-status-save',{action:'save',task_id:task.task_id});notify('Canzone pronta! La trovi nella tua libreria.','success');await refreshLibrary();},'sl-secondary'));
      if(task.status==='timeout'||task.status==='start_unknown')actions.append(actionButton('Controlla stato',async()=>{if(!window.confirm('Controllare lo stato remoto di questo task? Non avvia una nuova generazione.'))return;const res=await call('songlab-status-save',{action:'status',task_id:task.task_id,force:true});notify(`Stato aggiornato: ${stageText(res.status)}.`);await refreshLibrary();}));if(task.status==='processing')actions.append(actionButton('Controlla ora',async()=>{const res=await call('songlab-status-save',{action:'status',task_id:task.task_id});notify(`Stato: ${stageText(res.status)}.`);await refreshLibrary();}));row.append(actions);holder.append(row);}}
  async function signedUrl(song){const result=await call('songlab-library',{action:'audio',song_id:song.song_id});if(!result.url)throw Error('URL MP3 non disponibile.');return result.url;}
  async function downloadSong(song){const url=await signedUrl(song);const response=await fetch(url,{cache:'no-store'});if(!response.ok)throw Error(`Download non riuscito (HTTP ${response.status}).`);const blob=await response.blob();const objectUrl=URL.createObjectURL(blob);const anchor=el('a');anchor.href=objectUrl;anchor.download=fileName(song);document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(objectUrl),30000);}
  function renderSongs(){const holder=$('sl-songs');holder.replaceChildren();$('sl-empty').hidden=state.songs.length>0;const songs=[...state.songs].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));for(const song of songs){const item=el('article','sl-item');item.append(el('h3','sl-item-title',song.title||'Canzone'));item.append(el('div','sl-meta',[displayDate(song.created_at),fmtDuration(song.duration_ms),fmtSize(song.file_size),state.admin?song.owner_email:null].filter(Boolean).join(' · ')));const player=el('audio');player.controls=true;player.preload='none';player.setAttribute('aria-label',`Ascolta ${song.title||'Canzone'}`);player.addEventListener('play',()=>{document.querySelectorAll('#sl-songs audio').forEach(a=>{if(a!==player)a.pause();});});const actions=el('div','sl-item-actions');actions.append(actionButton('Ascolta',async()=>{const url=await signedUrl(song);player.src=url;player.load();await player.play();}));actions.append(actionButton('Scarica MP3',()=>downloadSong(song),'sl-secondary'));
      actions.append(actionButton('Rinomina',async()=>{const next=window.prompt('Nuovo titolo del brano:',song.title||'');if(next===null)return;const title=next.trim();if(!title||title.length>MAX.title)throw Error('Inserisci un titolo tra 1 e 200 caratteri.');await call('songlab-library',{action:'rename',song_id:song.song_id,title});notify('Titolo aggiornato.','success');await refreshLibrary();}));actions.append(actionButton('Elimina',async()=>{if(!window.confirm(`Eliminare definitivamente “${song.title}”? Verrà cancellato anche l'MP3. L'operazione non è reversibile.`))return;if(!window.confirm('Confermi la cancellazione definitiva?'))return;await call('songlab-library',{action:'delete',song_id:song.song_id,confirm:true});player.pause();notify('Canzone eliminata.','success');await refreshLibrary();}));item.append(player,actions);holder.append(item);}}
  function wire(){ $('sl-tab-create').addEventListener('click',()=>activate('create'));$('sl-tab-library').addEventListener('click',()=>activate('library'));$('sl-open-library').addEventListener('click',()=>activate('library'));$('sl-refresh').addEventListener('click',async()=>{try{await refreshLibrary();notify('Libreria aggiornata.','success');}catch(e){notify(e.message,'error');}});$('sl-copy-ai').addEventListener('click',copyAi);$('sl-insert-structure').addEventListener('click',()=>{const area=$('sl-lyrics');const template='[Intro]\n\n[Verse 1]\n\n[Chorus]\n\n[Verse 2]\n\n[Chorus]\n\n[Bridge]\n\n[Final Chorus]\n\n[Outro]\n';if(area.value.trim()&&!window.confirm('Aggiungere una struttura al testo esistente?'))return;area.value+=(area.value.trim()?'\n\n':'')+template;updateCounts();setBusy(state.busy);area.focus();});$('sl-lyrics').addEventListener('input',()=>{updateCounts();setBusy(state.busy);});$('sl-title').addEventListener('input',()=>setBusy(state.busy));$('sl-prompt').addEventListener('input',()=>{updateCounts();setBusy(state.busy);});for(const node of document.querySelectorAll('[data-music]'))node.addEventListener('input',invalidatePrompt);$('sl-preview').addEventListener('click',preparePrompt);$('sl-form').addEventListener('submit',startGeneration);$('sl-retry-auth').addEventListener('click',initAuth);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state.session)refreshLibrary().catch(()=>{});});}
  async function initAuth(){try{await login();await call('songlab-library',{action:'health'});$('sl-auth').hidden=true;$('sl-app').hidden=false;clearNotice();await refreshLibrary();}catch(e){$('sl-auth').hidden=false;$('sl-app').hidden=true;notify(e.message,'error');}}
  async function init(){wire();try{const response=await fetch('/songlab/config.json',{cache:'no-store'});if(!response.ok)throw Error(`config.json non disponibile (HTTP ${response.status}).`);state.config=await response.json();if(!state.config?.options||!state.config?.defaults)throw Error('config.json privo di opzioni o valori predefiniti.');fillSettings();await initAuth();}catch(e){notify(e.message,'error');$('sl-auth').hidden=false;}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
